# Generated by Django 5.0.7 on 2025-09-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payslip_published', 'New Payslip Published'), ('payroll_run_completed', 'Payroll Run Completed'), ('system_alert', 'System Alert'), ('account_change', 'Account Information Change'), ('deduction_update', 'Deduction Information Updated')], help_text='The category or type of the notification.', max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(default='New Notification', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='The main content of the notification.', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('related_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Related URL')),
                ('recipient', models.ForeignKey(help_text='The user who will receive the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='The user who initiated the notification (e.g., an administrator).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
