# Generated by Django 5.0.7 on 2025-09-17 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('helb_monthly_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_employee_id', models.CharField(help_text='Company-assigned employee ID', max_length=50, unique=True)),
                ('kra_pin', models.CharField(help_text='Kenya Revenue Authority PIN', max_length=20, unique=True)),
                ('nssf_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nhif_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('sacco', 'Sacco Contribution'), ('loan', 'Check-off Loan'), ('other', 'Other')], max_length=50)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntary_deductions', to='employees.employee')),
            ],
        ),
    ]
