# Generated by Django 5.0.7 on 2025-09-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nhif_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nssf_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AlterField(
            model_name='voluntarydeduction',
            name='deduction_type',
            field=models.CharField(choices=[('pension', 'Pension Contribution'), ('sacco', 'Sacco Contribution'), ('loan', 'Check-off Loan'), ('other', 'Other')], max_length=50),
        ),
    ]
