# Generated by Django 5.0.7 on 2025-09-20 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_company_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarydeduction',
            name='monthly_amount',
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount or percentage rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='name',
            field=models.CharField(default='Unnamed Deduction', help_text='Name of the deduction', max_length=100),
        ),
        migrations.AddField(
            model_name='voluntarydeduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voluntarydeduction',
            name='deduction_type',
            field=models.CharField(choices=[('pension', 'Pension Contribution'), ('sacco', 'Sacco Contribution'), ('loan', 'Check-off Loan'), ('insurance', 'Insurance Premium'), ('savings', 'Employee Savings'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='voluntarydeduction',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the benefit', max_length=100)),
                ('benefit_type', models.CharField(choices=[('transport', 'Transport Allowance'), ('housing', 'Housing Allowance'), ('meal', 'Meal Allowance'), ('medical', 'Medical Insurance'), ('phone', 'Phone Allowance'), ('education', 'Education Allowance'), ('other', 'Other')], max_length=50)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount or percentage rate', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this benefit is subject to income tax')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='employees.employee')),
            ],
        ),
    ]
