# Generated by Django 5.0.7 on 2025-09-21 11:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_voluntarydeduction_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_insurance_premiums',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly insurance premiums paid (life, health, education policies)', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_medical_fund_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly contribution to post-retirement medical fund', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_mortgage_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly mortgage interest paid for residential property', max_digits=10),
        ),
    ]
