# Generated by Django 5.0.7 on 2025-09-20 21:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_remove_voluntarydeduction_monthly_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the leave type', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Short code for leave type', max_length=10, unique=True)),
                ('annual_allocation', models.PositiveIntegerField(default=21, help_text='Number of days allocated per year for this leave type')),
                ('carry_forward', models.BooleanField(default=False, help_text='Whether unused days can be carried forward to next year')),
                ('max_carry_forward', models.PositiveIntegerField(default=0, help_text='Maximum days that can be carried forward')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether this leave type requires manager approval')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of leave')),
                ('end_date', models.DateField(help_text='Last day of leave')),
                ('days_requested', models.DecimalField(decimal_places=1, help_text='Number of days requested', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number during leave', max_length=15, null=True)),
                ('handover_notes', models.TextField(blank=True, help_text='Work handover instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year for which this balance applies')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total days allocated for this year', max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Days already used', max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Days in pending requests', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Days carried forward from previous year', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
