# Generated by Django 5.0.7 on 2025-09-17 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('payslip', 'Payslip Report'), ('nssf', 'NSSF Report'), ('nhif', 'NHIF Report'), ('paye', 'PAYE Report'), ('general', 'General Report')], max_length=50)),
                ('generation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='employees.employee')),
            ],
        ),
    ]
