# Generated by Django 5.0.7 on 2025-09-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('nssf', 'NSSF Rate'), ('shif', 'SHIF Rate'), ('ahl', 'AHL Rate'), ('paye_relief', 'PAYE Personal Relief')], max_length=20, unique=True)),
                ('rate_value', models.DecimalField(decimal_places=4, help_text='Rate as decimal (e.g., 0.06 for 6%)', max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(help_text='Date when this rate becomes effective')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
